### ISSUE TITLE
GPG Key - Error: Invalid Checksum

### ISSUE THREAD

**Issue by jimeh** [handshake-org/hs-airdrop#100]
I have made sure to have the latest hs-airdrop from the `master` branch and also cleared out `~/.hs-tree-data`, but I still keep getting the same error:

```
$ bin/hs-airdrop ~/.gnupg/secring.gpg <keyId> <address>
I found key 0x<keyId>, but it's encrypted.
Passphrase:
Error: Invalid checksum.
    at CipherParams.decipher (/Users/jimeh/src/hs-airdrop/node_modules/bcrypto/lib/pgp.js:1288:15)
    at CipherParams.decrypt (/Users/jimeh/src/hs-airdrop/node_modules/bcrypto/lib/pgp.js:1319:17)
    at PGPPrivateKey.secret (/Users/jimeh/src/hs-airdrop/node_modules/bcrypto/lib/pgp.js:1101:26)
    at parsePGP (/Users/jimeh/src/hs-airdrop/bin/hs-airdrop:492:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async parseArgs (/Users/jimeh/src/hs-airdrop/bin/hs-airdrop:702:21)
    at async main (/Users/jimeh/src/hs-airdrop/bin/hs-airdrop:740:19)
```

The GPG itself works though, and it's the main one on my GitHub account. I've tried another GPG key and it worked fine, and is not part of the airdrop as I expected.

The error above seems to indicate the issue is with the key itself, and the only thing special about that key specifically is that it was originally a GPG key from keybase, which I modified after the fact to add an email address too, and I believe I've since also changed the passphrase of the key once.

**Comment by jimeh** [comment]
I managed to get it to work by exporting the private key in armour format:

```
gpg --export-secret-keys --armour <keyId> > ~/private.asc
bin/hs-airdrop ~/private.asc <keyId> <address>
I found key <keyId>, but it's encrypted.
Passphrase:
Attempting to create proof.
```
