### ISSUE TITLE
Error that 'bcrypto/lib/pgp' cannot be found when claim airdrop

### ISSUE THREAD

**Issue by hatgit** [handshake-org/hs-airdrop#123]
I am getting the following error (related to [line 11 from here](https://github.com/handshake-org/hs-airdrop/blob/master/bin/hs-airdrop)) when trying to claim the airdrop: 

```internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'bcrypto/lib/pgp'
Require stack:
- /Users/Steven/Github/hs-airdrop/bin/hs-airdrop
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Steven/Github/hs-airdrop/bin/hs-airdrop:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/Steven/Github/hs-airdrop/bin/hs-airdrop' ]
```

**Comment by pinheadmz** [comment]
did hs-airdrop install correctly? Do you have a directory `hs-airdrop/node_modules/bcrypto` ?

**Comment by pinheadmz** [comment]
@hatgit any progress on this?
