### ISSUE TITLE
Error: Cannot find module 'bcrypto.node'

### ISSUE THREAD

**Issue by mzcoder-hub** [handshake-org/hs-airdrop#127]
i got some error here

`D:\DataGalang\test-cepot\hs-airdrop\node_modules\loady\lib\loady.js:156
  throw err;
  ^

Error: Cannot find module 'bcrypto.node'
    at moduleError (D:\DataGalang\test-cepot\hs-airdrop\node_modules\[4mloady[24m\lib\loady.js:154:15)
    at resolve (D:\DataGalang\test-cepot\hs-airdrop\node_modules\[4mloady[24m\lib\loady.js:89:9)
    at load (D:\DataGalang\test-cepot\hs-airdrop\node_modules\[4mloady[24m\lib\loady.js:99:16)
    at Object.<anonymous> (D:\DataGalang\test-cepot\hs-airdrop\node_modules\[4mbcrypto[24m\lib\native\binding.js:11:33)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m
}`

**Comment by pinheadmz** [comment]
How did you install hs-airdrop?
What OS are you using? what version of nodejs?

**Comment by mzcoder-hub** [comment]
@pinheadmz  im using windows 10 , i install using github clone command, and v14.15.0 nodejs

**Comment by leonardo210795** [comment]
Ok thanks

**Comment by pinheadmz** [comment]
did you execute `npm rebuild` ?

**Comment by mzcoder-hub** [comment]
i did install `npm install` but its success installed 10 dependency

**Comment by pinheadmz** [comment]
a successful installation would include bcrypto and the native addon `bcrypto.node`

**Comment by mzcoder-hub** [comment]
well yeah bcrypto.node is installed and listed on the folder https://prnt.sc/xy0sxv but stay still its throw error

**Comment by pinheadmz** [comment]
and in the `build` folder?

![Screenshot from 2021-01-31 20-19-02](https://user-images.githubusercontent.com/2084648/106404717-a15e7880-6401-11eb-84c1-8b2ede94729e.png)

**Comment by mzcoder-hub** [comment]
![image](https://user-images.githubusercontent.com/55178769/106405013-54ad8880-6467-11eb-9e2a-583e8d203b81.png)
theres no item in the build folder, its exist but no items

**Comment by andrekovac** [comment]
Run `npm rebuild bcrypto` and continue `npm rebuild` commands for any other modules which throw the `Error: Cannot find module` error.
