### ISSUE TITLE
Error: PEM parse error (unexpected data).

### ISSUE THREAD

**Issue by Geoveza** [handshake-org/hs-airdrop#128]
root@GEOVEZA:/# node hs-airdrop ~/.ssh/id_rsa hs1****************************                                                                                                                                Passphrase:                                                                                                                                        
Error: PEM parse error (unexpected data).                                                                                                             
at decode (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/node_modules/bcrypto/lib/encoding/pem.js:349:13)            
at decode.next (<anonymous>)                                                                                                                       at PEMBlock.fromString (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/node_modules/bcrypto/lib/encoding/pem.js:61:21)                                                                                                                                                   at Function.fromString (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/node_modules/bcrypto/lib/encoding/pem.js:134:23)                                                                                                                                                  at SSHPrivateKey.fromString (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/node_modules/bcrypto/lib/ssh.js:638:28)                                                                                                                                                      at Function.fromString (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/node_modules/bufio/lib/struct.js:159:23)       
at readKey (/mnt/c/Users/geove/Documents/Tools/BOT/AIRDROP/hs-airdrop-0.10.0/hs-airdrop/bin/hs-airdrop:545:33)                                     at process._tickCallback (internal/process/next_tick.js:68:7) 

How to solve this bro?

**Comment by pinheadmz** [comment]
Are you sure ` ~/.ssh/id_rsa` is a valid key file?

Other issues to check:

https://github.com/handshake-org/hs-airdrop/issues/61

https://github.com/handshake-org/hs-airdrop/issues/32
