### ISSUE TITLE
Found nonce but error broadcasting transaction "bad-goosig-disabled"

### ISSUE THREAD

**Issue by samsondav** [handshake-org/hs-airdrop#131]
I am following the instructions listed here:

https://handshake.org/claim/

And I have a nonce found in the tree:

```
Attempting to create proof.
This may take a bit.
Decrypting nonce...
Found nonce!
Rebuilding tree...
Finding merkle leaf for reward 0...

2 keys found in your subtree:
  <REDACTED>
  <REDACTED> (current)

Creating proof from leaf XXXXX:Y...
Signing proof XXXXX:Y...
```

It generates the following hex:

```
Base64 (pass this to $ hsd-rpc sendrawairdrop):
jMgAABJLlRrbd/10fc3MkPh32Y8OQCcysnP2bUhR+6XzakHKLJGuK3kgyCOEfJ8XPT1IJtvZZL9zaTC5x6QxqQIqfhSnqy3guOtwuMWse1KDXTwQOFWvi3wPGAvhzUKWWmRf86KAuflDBw39LegAii8bo6VeRLyUNRuWelkjyeeTyQNMOC4NT3Y8dfhc1r5DbS+8rtr48NKitrrYlvTZboT5Mm44l/9ifLxdRj3KDzLXUZgMu5T6JHVlSUzEaYE6pfVYSA0JC1hIwCaURuRmwo8bUMcVd+i5HXHvU/xOb7i7fQdrrmp7cK+273cJiMLxPuS62m5BEQU4uOARuu811MWFMVysjgXjuM4HQ0HlLzgMsozEoGgzkBqw2PnICoiMjDSL9wvvRzShE+/Wy55m3Il/4h93+YgX7PdFW1ZqvoSbdzgdtEsW4dWyqA+Lbiokokbycf9CEwhbwgjMU4gI5pvn2sFSykwzqfWIIGHdY0P5cFMLLNZvmkQxJD8vUUWZ5zZdi8LIifSZrsLzEaU1poEjfs+1Um+MsjuMfG3KnEh/Fjs8dqmjO79obCuLAcRAKxKCBJjGPUcPfR/q2aYU5UgH72V8xZS28j0PS8GKjBXjbt1Xk/QAoX0BItMh27cO5C5rhrnHbR2NfFQ6cz7cc5vQEHkeY6Es71iBFf7N/DaEcLaKTIK64bcNrca9kKNQAb3yEoBfQHh0vB3Sp5QCNe4BRJuFO/ib69fyWOGaKBvVoSHo2Uri0xxnD3dSZVkPNJWl7DgHA3E78NnRGkFlgDzRkQUmncD5SBrvkdZ7uuiCQF8JhN8bC1Mm4okqoavc+ZhkmnetUXGWCWu9EFSC2qEIHX9YtXuLHLdFPx24uVCenvkYQYM3Xx2Z9gvPICRSDkQAsrmDNv0BAQEmoduwB+VIydEVvq5muCnp1PvfuuRCjgnWqZEtHZcP4a2sbQXOL/DtO3R0LY18MFy48BccvF9xfpo04RrJnDL92LEIvxouLzSepQXo0O4EEIaE64DiTnwlJLy9LM7vVPrM5KrV+ncXHTslCN5kFaZr/5EvIxC5K13Dj5G7Oi7XGcFSMcma8hHSkF0rZxgO0poVIfKXBqdoNQE2xFOeBzml7SXJfOJkmH5u7wfyL4aBiZZhlch7gfh+r7c+pmnNLvub6c3bKcASZN0j7YvJ4M/sVlM5qGIp/HUFwEygn0MA8MUju3gB/LVHO0XNExKu91Q2gD04Tou/sRmlJxIPQ5WyABQUCYAi7WkUNbKFddVJP48XsN/YBv6ghgEA/awHHTdYlTOVbIU/m5MIAhN7lfuOFIuDfhb1YVIKh4FsymjQudZaho1JMPnDWPSLljogkZyZJtYTJCap7tSgPsI9BiCCCCfJqBCvLoUOlAv/4m1DmeDP6cvBCvQToVQ2O35ZXj2wO+i8/vRr3xJzjMr6nlGVuTvH+Dw6/knAhcGS9fRwb/MeF3xPvATXHSOa9DYgNWRGGl7TVZlaBh2DiHSUnkrUv17/cQMXeJXuXZW/+XmU7aC8Z2HlAjkDw+JZAbYSm5l3VWmdv4PkTPhgbVY29uMbmgfktMyH4IHkZgp/q5SKeSGsuVfNZN+0FmoPGWXnU2FV14YFdiKAIXjy+nnv40GLqiN8cpAE2X1BSqFs/RYhouqLoTmwvTDk6chWIHhNV5S2aYq1/67Zt4tHtFx1O6Lb9WVxSwDfFAYw/bmC+vc5eSbk2+AGY2Bod/2bTnaCvfNEITWtf0tK5L807NmqnOAFpcmHHTychczRN0zQr5X6whJDK3RlXmZBglrQHCtV9eyx88cA1vvtm2ZUU4JMQXaLAavMwSOCwOFTC6U8bDCNileMhwvOpeHSmSp/jFF+Qioy3y/AOpPjnQDEfTpD0PgMUEZgH9WtH8S5HXdLWdnXQc01OmDNtMY1ZtRiNu02tjc0vLsoOb2QWknMTZ9qnMXhT2zvHSfLtY/JCBLtVp0Bbx+YoHttxhw+bxCa7N42v9PL3Rj5i6judNf6mozzCklYIQ2ZNbb/smu8vXPYWZdy8CDogNOLyidhF/hgik1i2csX2/aMEyqjH/9ky49KUO5OQqmQamg3zmH0t7903mV0rvqggNQaDrT9okSpudl0dWxZEl7LKNbXhoZvOh4q2O6xwJnKOdpdW7Mb2HvZ1trJ/+gt+XDAhtxU6xpfGGnbNMSKcdP13Q4Eibxdd8Y9WVZEBZxN6QFc0mPmhmgSPaUrT9BaEK+HZgtMV3MYI9UsrKyYMZbaszuNSNidYqOgss9IfxyHytsc74H12yQ1vE18mY2+9700GZOCIsbelQ1vk72Z6mGnQd3qGQtYGZQ4JlhmqguuxDH/8qDaQPH8vyY2kZ1SGSWwFV4Y95H4x3QgeeVRro/rsZcw7JMKnDJxJjzBVDd69gMwE4JU/9micmijcMhKtGrRdy/QHrumsFCoV62XZpM+RyqolyIGGyaLM7UYTcZ3cdrs3MQJX8fDug28lxb6B7EwZgtRfV/CLBm4ouYzcnD6uLVzVCabJJaaaBntH9zSyI3ceZmOXpLxR+4lWEMpq0U4+AH94x5vOpiKElqqwVU+kcvEXgQ8CNE0iJXV3n/UgTIxi1aM8HjbV4vjY4Et2MpMNlwBuA0vCVlE3IhAX0MDkxhEe7GJxnkGRfQ3zkP8ej+PHnxhzl/E3jIDrE+AM8aEYcezWW8blK+OcwIlNGvNEBwWdLGGh74bzRLqvg3pNSRZ0IbWs976OFklLmYAaQlGnzwaLEuVn5mRHNMNfw7BW/YVZOm165VlJ5syMDCJmW1KxMlfZZpr/etgDKSKZ+rWpKGe7VAjG/ziIQIey8azWYuEhZXRZjBs8B1qyItnvb/oCrGBw7UqtgGt/JKigxkJW+F89ElLSafSVyJRYviEvaXGcimHTAsHQEsC1i23kfk0xb2z/GTgh1Xq32f9fOimjM5ANIZrOLRJRrH2Yqj/9Ci4qUnpKayDp9i1K4j7+FHVBHhN+yyrs4fbxlkX9iPczaVudysbjJgihWxcJhRNQcBGHON2m0pFUS/pRSJFHEIz7AyitvCMor8AXUueE4CArYQNjMUedJrW7N/n3sAplCetUV5DaHOMLCmZotiK78XV0WNJ+yBhiL1p/RfMTBJN3zasl1vbmCkGAiL5K7gMUTqGPD64dfelWJVZI8Yo7edLC4cIaWhlZoQWG0SdWvAzhKqIM4/FQkrNZRHthrxK95y+e94SOKH25K8jysPt1/jOHhVVnk32F6OMUvk46nDaLhbfskA1DdLP9oRllelU2yYqfsofS2Nk6Ocp/wh6RZLhRIwsgJiJILQbiQ3UGIDlGqSxkF3JE/dtWD8LihGx65tI+J0qQS4UE+rgbVWY/2t9m/N6zeS/6BBk6uwAAAAAAAAAAAAAAAAAAAAAAC8rjaYRLrpf5+fgR6fSLxWm1a6Q7T/MZ0DbxBIm4kphsoNbT6OuDS715mQUYctybEJl0r4jNsOHFiApOfhHY2yHJqek7Nj5pyGO81e5GbsWONK6YDdbiFrxjh0uzD6KXLld/0Fr1ODkii5rUaSFCleFjaB3C9hLcOXnozJwlrkVebDVVVqhIhXXgmEGaQVBul2qQWGZmJBcHRLw2IwujrCtiUTO5I63oNAFPHfXQ/+Rj9f+tXnJhPgTqOWsgiksnHwxctNHYnmaw1/4xZl0GmkgSs26lmdyH4pOjw+62R6cUBxTJHwX9Kjli1Dg2sTBINHORDkwfJTUACVZ0CKIB+py2884hZVJ/vPzNg2i4HsLM3vL5cIKFDgzJFaVIJXc0jdqmp2jOWmcsQXLFeWdHKZKm1YrHY8C5CjWULsFIh+W24f181vlrZ6PgNoclWNro8qVtfx0ujDLXShCo49d/RI49GDvhzhceTxrVaxQRIs1Z8YbtD7CeQA=
```

But when I try to transmit, my local node gives the following errors:

```
[error] (node) Verification failure: bad-goosig-disabled (code=invalid score=0 hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b)
    at Mempool.insertAirdrop (/Users/sam/code/handshake/hsd-2.3.0/hsd/lib/mempool/mempool.js:1272:15)
    at Mempool._addAirdrop (/Users/sam/code/handshake/hsd-2.3.0/hsd/lib/mempool/mempool.js:1234:16)
    at Mempool.addAirdrop (/Users/sam/code/handshake/hsd-2.3.0/hsd/lib/mempool/mempool.js:1215:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FullNode.sendAirdrop (/Users/sam/code/handshake/hsd-2.3.0/hsd/lib/node/fullnode.js:412:7)
    at async FullNode.relayAirdrop (/Users/sam/code/handshake/hsd-2.3.0/hsd/lib/node/fullnode.js:433:7)
[warning] (node) Verification failed for proof: 4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (node) Attempting to broadcast anyway...
[warning] (net) Received reject (54.184.104.94:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (139.162.183.168:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (45.79.134.225:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (64.227.15.172:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (165.22.151.242:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (47.240.14.207:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (160.16.237.116:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
[warning] (net) Received reject (172.104.214.189:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=4abd5d62bfc7ac9fe83c4a3a34707a6d6ecfb6d2bd6f75da77c16dee9c700b6b.
```

What have I done wrong?

I am using:

- hsd-2.3.0
- hs-airdrop-0.10.0
- hs-client-0.0.9

**Comment by samsondav** [comment]
I was able to fix this with some help from devs in the telegram group. Apparently Goosig was disabled on day 395.

I had to recreate my airdrop base64 with the `--bare` option like so:

`./bin/hs-airdrop --bare ~/.ssh/id_rsa hs1XXX`

This time it worked. It is noted that this exposes your raw public key.

**Comment by pinheadmz** [comment]
Thanks for the update! I'm going to reopen this as a reminder we need to update the docs :-)

**Comment by strager** [comment]
@samsondav's workaround worked for me!

Here's what was in hsd's logs *before* using `--bare`:

```
[error] (node) Verification failure: bad-goosig-disabled (code=invalid score=0 hash=088f2f8e902147c4d755bc89f0ff2c3918e462dea401ecd44abded9c8074563f)
    at Mempool.insertAirdrop (/Users/strager/Projects/handshake/hsd-2.4.0/hsd/lib/mempool/mempool.js:1290:15)
    at Mempool._addAirdrop (/Users/strager/Projects/handshake/hsd-2.4.0/hsd/lib/mempool/mempool.js:1252:16)
    at Mempool.addAirdrop (/Users/strager/Projects/handshake/hsd-2.4.0/hsd/lib/mempool/mempool.js:1233:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async FullNode.sendAirdrop (/Users/strager/Projects/handshake/hsd-2.4.0/hsd/lib/node/fullnode.js:425:7)
    at async FullNode.relayAirdrop (/Users/strager/Projects/handshake/hsd-2.4.0/hsd/lib/node/fullnode.js:446:7)
[warning] (node) Verification failed for proof: 088f2f8e902147c4d755bc89f0ff2c3918e462dea401ecd44abded9c8074563f.
[warning] (node) Attempting to broadcast anyway...
[warning] (net) Received reject (160.16.237.116:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=088f2f8e902147c4d755bc89f0ff2c3918e462dea401ecd44abded9c8074563f.
[warning] (net) Received reject (165.22.151.242:12038): msg=AIRDROP code=invalid reason=bad-goosig-disabled hash=088f2f8e902147c4d755bc89f0ff2c3918e462dea401ecd44abded9c8074563f.
```

after using `--bare`:

```
[info] (wallet) Incoming transaction for 1 wallets in WalletDB (3e2191a769dc4f2acd0daacf433df21f2adb1e48d33b41b2b5b631989cea5880).
[info] (wallet) Added transaction to wallet in WalletDB: primary (0).
[info] (wallet) Connected WalletDB block 0000000000000002c931808dbcfa058239091332fb4e0b8aeb356eb2ba3f2d95 (tx=1).
```

**Comment by tunnckoCore** [comment]
Nope. Even with `--bare`, plus I'm not using the ssh, I use the pgp keys.

With or without `--bare` i'm getting the same base64 string, but different hash when `sendrawairdrop`.

My node is fully synced.

**Comment by jurikarta** [comment]
Good luck
