### ISSUE TITLE
Verification failure: txn-already-in-mempool / bad-txns-inputs-missingorspent 

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hs-airdrop#133]
If you see this error in the hsd log after broadcasting your airdrop proof, it means **YOUR AIRDROP HAS ALREADY BEEN CLAIMED**. This is essentially a double-spend error.

Every GitHub airdrop recipient can claim ONCE on Handshake. This means even if you had 10 PGP keys in your account, you can only claim once, and then the other 9 keys won't work. If you didn't claim with `--bare` before and are trying that now, it won't work -- you can only claim once.

If you used a Namebase address the first time you claimed and you are seeing this error now, that means your first claim succeeded and your funds belong to Namebase. There is nothing else you can do with handshake-org software, you must contact Namebase support.

Airdrop claims can not be spent until they accumulate 100 blocks. Namebase or any other exchange may require additional confirmations on top of that before crediting your account.

If you are absolutely certain without a doubt that this is the very first time you have ever run `hs-airdrop` and you are getting this error in your hsd log it means either:

- Your GitHub keys have been compromised and someone else has managed to claim your airdrop
- There is something extremely wrong with the airdrop implementation at the consensus level

If you are certain that your GitHub keys have always been safe, and you saw this error the first time you attempted to claim an airdrop, please comment below or if you think there may be a critical consensus bug involved, [please contact handshake-org securely](https://github.com/handshake-org/hsd/security/policy).

**Comment by hughevans** [comment]
I have this yeah:

```
[error] (node) Verification failure: txn-already-in-mempool (code=alreadyknown score=0 hash=342553aa24d46930fb1bd52a56fa5b380d881661b3b8c1a620a687d543e382df)
    at Mempool.insertAirdrop (/Users/hughevans/Downloads/hsd-2.4.0/hsd/lib/mempool/mempool.js:1274:13)
    at Mempool._addAirdrop (/Users/hughevans/Downloads/hsd-2.4.0/hsd/lib/mempool/mempool.js:1252:16)
    at Mempool.addAirdrop (/Users/hughevans/Downloads/hsd-2.4.0/hsd/lib/mempool/mempool.js:1233:25)
    at async FullNode.sendAirdrop (/Users/hughevans/Downloads/hsd-2.4.0/hsd/lib/node/fullnode.js:425:7)
    at async FullNode.relayAirdrop (/Users/hughevans/Downloads/hsd-2.4.0/hsd/lib/node/fullnode.js:446:7)
[warning] (node) Verification failed for proof: 342553aa24d46930fb1bd52a56fa5b380d881661b3b8c1a620a687d543e382df.
[warning] (node) Attempting to broadcast anyway...
[warning] (net) Received reject (172.104.214.189:12038): msg=AIRDROP code=invalid reason=bad-txns-inputs-missingorspent hash=342553aa24d46930fb1bd52a56fa5b380d881661b3b8c1a620a687d543e382df.
```

**Comment by icyphox** [comment]
Hi, I ran across this error after having realized that I didn’t run it with `--bare` the first time. However, my account balance won’t update: 

```
  "balance": {
    "account": -1,
    "tx": 0,
    "coin": 0,
    "unconfirmed": 0,
    "confirmed": 0,
    "lockedUnconfirmed": 0,
    "lockedConfirmed": 0
  }
```

Any ideas? I’ve given it about 8 hours.

**Comment by michaelknoch** [comment]
did you find a solution @icyphox ?

**Comment by pinheadmz** [comment]
@icyphox @michaelknoch airdrops require 100 confirmations to mature before spending (like the miners reward in the coinbase transaction)
