### ISSUE TITLE
`(node-rpc) Assertion failed` error when executing `./bin/hsd-cli rpc sendrawairdrop`

### ISSUE THREAD

**Issue by lukes** [handshake-org/hs-airdrop#140]
Hi!

I'm running through the instructions here https://handshake.org/claim/ and when I 

```
./bin/hs-airdrop --bare <path/to/id_rsa> <hs-address> 
```

It appears to work fine:

```
Attempting to create proof.
This may take a bit.
Decrypting nonce...
Found nonce!
Rebuilding tree...
Finding merkle leaf for reward 0...

4 keys found in your subtree:
  <string1>
  <string2>
  <string3> (current)
  <string4>

Creating proof from leaf <numbers>:<number>...
Killed
```

The next instruction is to `cd` to the `hs-client` directory and run:

```
./bin/hsd-cli rpc sendrawairdrop BASE64_STRING
```

I'm not sure which of those 4 keys printed above is the `BASE64_STRING`, so I've tried: 

- running this command with each of the 4 above strings individually
- running it with all 4 concatenated together

But I always get this error in the node logs:

```
[error] (node-rpc) RPC internal error.
[error] (node-rpc) Assertion failed.
    at AirdropProof.read (/root/hsd-2.4.0/hsd/lib/primitives/airdropproof.js:134:5)
    at AirdropProof.decode (/root/hsd-2.4.0/hsd/lib/primitives/airdropproof.js:124:10)
    at Function.decode (/root/hsd-2.4.0/hsd/node_modules/bufio/lib/struct.js:147:23)
    at RPC.sendRawAirdrop (/root/hsd-2.4.0/hsd/lib/node/rpc.js:2546:32)
    at RPC.execute (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/rpc.js:208:17)
    at RPC.call (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/rpc.js:151:29)
    at Hook.handler (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/middleware/jsonrpc.js:38:26)
    at HTTP._handleStack (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/server.js:294:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] (node) Assertion failed.
    at AirdropProof.read (/root/hsd-2.4.0/hsd/lib/primitives/airdropproof.js:134:5)
    at AirdropProof.decode (/root/hsd-2.4.0/hsd/lib/primitives/airdropproof.js:124:10)
    at Function.decode (/root/hsd-2.4.0/hsd/node_modules/bufio/lib/struct.js:147:23)
    at RPC.sendRawAirdrop (/root/hsd-2.4.0/hsd/lib/node/rpc.js:2546:32)
    at RPC.execute (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/rpc.js:208:17)
    at RPC.call (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/rpc.js:151:29)
    at Hook.handler (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/middleware/jsonrpc.js:38:26)
    at HTTP._handleStack (/root/hsd-2.4.0/hsd/node_modules/bweb/lib/server.js:294:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Is anyone able to help me to debug this?

**Comment by rithvikvibhu** [comment]
The proof generation isn't complete. Looks like the process was "Killed" (last line). Could be due to memory or other constraints. Is this being run in a virtual machine / cloud instance? Running it again may work.

A successful output will include a large json object and end with a long base64 string, along with instructions on how to use it (the `sendrawairdrop` in your comment).

**Comment by lukes** [comment]
Thanks! I'm using the smallest Digital Ocean droplet (1G memory and 1 CPU). I'll try resizing it up.

**Comment by lukes** [comment]
Resizing the droplet to be larger worked! All done. Thank you for your help.

**Comment by riski2801** [comment]
this is good
