### ISSUE TITLE
Error: Cannot find module 'leveldown.node'

### ISSUE THREAD

**Issue by andrecgro** [handshake-org/hs-airdrop#142]
I'm not being able to run finish the installation process.

When trying to run `.bin/hsd --log-level info`, I get:

```
❯ ./bin/hsd --log-level info
/Users/andrerocha/Projetos/hsd/hsd-2.4.0/hsd/node_modules/loady/lib/loady.js:156
  throw err;
  ^

Error: Cannot find module 'leveldown.node'
    at moduleError (/Users/andrerocha/Projetos/hsd/hsd-2.4.0/hsd/node_modules/loady/lib/loady.js:154:15)
    at resolve (/Users/andrerocha/Projetos/hsd/hsd-2.4.0/hsd/node_modules/loady/lib/loady.js:89:9)
    at load (/Users/andrerocha/Projetos/hsd/hsd-2.4.0/hsd/node_modules/loady/lib/loady.js:99:16)
    at Object.<anonymous> (/Users/andrerocha/Projetos/hsd/hsd-2.4.0/hsd/node_modules/bdb/lib/level.js:9:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND'
}
```

OS: macOS Catalina 10.15.7
node: v14.16.1
npm: 6.14.12

**Comment by pinheadmz** [comment]
Did installation succeed? You may need to try `npm rebuild` to recompile the native addons (like leveldb) for your OS

**Comment by andrecgro** [comment]
Yes, the installation was successful. This was the only problem

**Comment by andrecgro** [comment]
The `npm rebuild` did the trick!!
Thank you very much.
