### ISSUE TITLE
Any plan to support ECDSA?

### ISSUE THREAD

**Issue by SgrAlpha** [handshake-org/hs-airdrop#45]
I do have had 16 followers on GitHub on Feb 4, 2019 and have multiple SSH public keys linked to my account, but unfortunately they are all in `ecdsa-sha2-nistp521` type. I got the following error:

> Error: Unsupported algorithm.
    at AirdropKey.fromSSH (/Volumes/development/github/hs-airdrop/lib/key.js:768:15)
    at Function.fromSSH (/Volumes/development/github/hs-airdrop/lib/key.js:882:23)
    at readKey (/Volumes/development/github/hs-airdrop/bin/hs-airdrop:539:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async parseArgs (/Volumes/development/github/hs-airdrop/bin/hs-airdrop:714:21)
    at async main (/Volumes/development/github/hs-airdrop/bin/hs-airdrop:740:19)

**Comment by cevin** [comment]
same question.

ECDSA  is very popluar

**Comment by pinheadmz** [comment]
From [the README](https://github.com/handshake-org/hs-airdrop#accepted-key-algorithms):

> Accepted Key Algorithms
> To simplify consensus implementation, we only allow the top 3 most popular key algorithms used on github:
> 
> RSA (1024 to 4096 bit modulus, e <= 33 bits) - See the Handshake paper as to why 1024 bit moduli are considered acceptable.
> Ed25519
> P256 (NIST curve)

Because this is consensus-critical, changes to the airdrop tree or proof methods can not be changed without a hard fork. If it means enough to you, you could write a software patch and try to get the community to adopt it and initiate a hard fork. Sorry about this. Closing for now.
