### ISSUE TITLE
Invalid file or disk full: cannot seek to 0x3E3938 [E:\airdrop\node_modules\bcrypto\build\bcrypto.vscproj]

### ISSUE THREAD

**Issue by Rinacm** [handshake-org/hs-airdrop#62]
```
C:\Users\26532\AppData\Local\node-gyp\Cache\12.10.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cann
ot seek to 0x2E3938 [E:\hs-airdrop\node_modules\bcrypto\build\bcrypto.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\26532\scoop\apps\nodejs\12.10.0\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\26532\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\Users\\26532\\scoop\\apps\\nodejs\\12.10.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\hs-airdrop\node_modules\bcrypto
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypto@5.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypto@5.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\26532\scoop\persist\nodejs\cache\_logs\2020-02-20T17_34_07_817Z-debug.log
```
when I'm trying to run the comman `npm install` these message appeared, seems there's some file losing, how can I deal with this (the msvs_version was set to 2019 and the npm version is 6.10.3)

**Comment by boymanjor** [comment]
@Rinacm this doesn't look like an error with `hs-airdrop`. I think it is a Visual Studio [error](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1106?view=vs-2019)

Source: https://github.com/nodejs/node-gyp/issues/1898#issuecomment-540116440
