### ISSUE TITLE
last step meets error

### ISSUE THREAD

**Issue by leeseean** [handshake-org/hs-airdrop#63]
TypeError: stdin.setRawMode is not a function
    at readLine (C:\Users\Administrator\Desktop\hs-airdrop\lib\readline.js:17:9)
    at readPassphrase (C:\Users\Administrator\Desktop\hs-airdrop\lib\readline.js:92:10)
    at readKey (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-airdrop:535:32)
    at async parseArgs (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-airdrop:714:21)
    at async main (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-airdrop:740:19)

**Comment by boymanjor** [comment]
A similar issue has been resolved here: https://github.com/handshake-org/hs-airdrop/issues/51. I'm closing this for now. Feel free to reopen if that thread does not solve your issue.
