### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by yyy999** [handshake-org/hs-airdrop#71]
/home/sky/hs-airdrop/bin/hs-airdrop:109
async function readFile(...path) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by pinheadmz** [comment]
Can you provide more context please? What command resulted in this error? What is your OS and nodejs version? Were there any issues during installation?

**Comment by ShiSanChuan** [comment]
> Can you provide more context please? What command resulted in this error? What is your OS and nodejs version? Were there any issues during installation?

i have same problem,my OS is ubuntu16.04

**Comment by fanshiqing** [comment]
@ShiSanChuan @yyy999 update node version works for me.
