### ISSUE TITLE
【Error】Could not locate the bindings file. Tried:    

### ISSUE THREAD

**Issue by OneCodeMonkey** [handshake-org/hs-airdrop#74]
I am following the official steps and when I tried:

$ >> ./bin/hs-airdrop {key-path} {my hns-src} 0.01

print Error:
`
Could not locate the bindings file. Tried:        

- /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/build/bcrypto.node                                                            - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/build/Debug/bcrypto.node                                                      - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/build/Release/bcrypto.node                                                    - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/out/Debug/bcrypto.node                                                        - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/Debug/bcrypto.node                                                            - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/out/Release/bcrypto.node                                                      - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/Release/bcrypto.node                                                          - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/build/default/bcrypto.node                                                    - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/compiled/10.15.1/linux/x64/bcrypto.node                                       - /home/vagrant/Code/hs-airdrop/node_modules/bcrypto/addon-build/release/install-root/bcrypto.node                                 
/home/vagrant/Code/hs-airdrop/node_modules/bcrypto/addon-build/debug/install-root/bcrypto.node                                   
/home/vagrant/Code/hs-airdrop/node_modules/bcrypto/addon-build/default/install-root/bcrypto.node                                
/home/vagrant/Code/hs-airdrop/node_modules/bcrypto/lib/binding/node-v64-linux-x64/bcrypto.node                                      
at bindings (/home/vagrant/Code/hs-airdrop/node_modules/loady/lib/loady.js:116:15)                                                 at Object. (/home/vagrant/Code/hs-airdrop/node_modules/bcrypto/lib/native/binding.js:14:33)                             at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                         at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                           at Module.load (internal/modules/cjs/loader.js:599:32)                                                                             at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                           at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                                                    at Module.require (internal/modules/cjs/loader.js:637:17)                                                                          at require (internal/modules/cjs/helpers.js:22:18)                                                                                 at Object. (/home/vagrant/Code/hs-airdrop/node_modules/bcrypto/lib/native/md5.js:9:17)
`

It reports the above error :(

**Comment by mxito3** [comment]
+1

**Comment by boymanjor** [comment]
@OneCodeMonkey what OS and version of Node.js are you running?

**Comment by OneCodeMonkey** [comment]
centos 7.5，nodejs 11.12

**Comment by ouwenkg** [comment]
+ 1
