### ISSUE TITLE
EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by archessay** [handshake-org/hs-airdrop#84]
hi,

When I run the command "./bin/hs-airdrop  ~/.ssh/id_rsa hs1q4pwj68nvkazuvvs2xcd6sh3cszmgxxxx  0.1" with my private key, I get an error. How to solve it, thank you.

Exception stack：
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:172:29)
    at CipherBase.final (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bcrypto@5.0.3@bcrypto/lib/native/cipher.js:59:21)
    at Decipher.final (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bcrypto@5.0.3@bcrypto/lib/native/cipher.js:114:21)
    at Object.decrypt (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bcrypto@5.0.3@bcrypto/lib/native/cipher.js:187:9)
    at Object.decrypt (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bcrypto@5.0.3@bcrypto/lib/encoding/pemcrypt.js:68:23)
    at SSHPrivateKey.fromString (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bcrypto@5.0.3@bcrypto/lib/ssh.js:644:16)
    at Function.fromString (/Users/liuchunlong/IdeaProjects/hs-airdrop/node_modules/_bufio@1.0.6@bufio/lib/struct.js:155:23)
    at readKey (/Users/liuchunlong/IdeaProjects/hs-airdrop/bin/hs-airdrop:537:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async parseArgs (/Users/liuchunlong/IdeaProjects/hs-airdrop/bin/hs-airdrop:715:21)

**Comment by fuchao2012** [comment]
same here

**Comment by pinheadmz** [comment]
@fuchao2012 make sure you are using the right passphrase for your encrypted key!
